package com.xiaozhi.simple.service

import android.net.Uri
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Native Momo AI Server device binding, independent of Xiaozhi voice sockets.
 *
 * The QR ticket is generated by the account owner in Momo Console.
 * The six-digit code is generated on this phone, then approved by a
 * signed-in owner in the console. The phone gets its token only by
 * presenting an independent, high-entropy polling secret.
 */
class MomoPairingService {
    companion object {
        const val SERVER = "https://ai.momolegend.fun"
    }

    data class CodeSession(
        val pairingId: String,
        val code: String,
        val pollSecret: String,
        val expiresAt: Long
    )

    data class BoundDevice(val deviceId: String, val token: String)
    data class CodePoll(val status: String, val bound: BoundDevice?)

    private val client = OkHttpClient.Builder()
        .connectTimeout(8, TimeUnit.SECONDS)
        .readTimeout(12, TimeUnit.SECONDS)
        .followRedirects(false)
        .followSslRedirects(false)
        .build()
    private val jsonType = "application/json; charset=utf-8".toMediaType()

    private suspend fun post(action: String, data: JsonObject): JsonObject = withContext(Dispatchers.IO) {
        if (action !in setOf("request-code", "claim-qr", "poll", "ack")) {
            throw IOException("Unsupported pairing request")
        }
        val request = Request.Builder()
            .url("$SERVER/api/pairing/$action")
            .post(data.toString().toRequestBody(jsonType))
            .header("Accept", "application/json")
            .header("Cache-Control", "no-store")
            .build()
        client.newCall(request).execute().use { response ->
            val raw = response.body?.string()?.take(8192) ?: ""
            val objectResponse = runCatching { JsonParser.parseString(raw).asJsonObject }.getOrNull()
            if (!response.isSuccessful) {
                val detail = runCatching { objectResponse?.get("detail")?.asString }.getOrNull()
                val message = detail?.take(160) ?: "Pairing failed (HTTP ${response.code})"
                throw IOException(message)
            }
            objectResponse ?: throw IOException("Momo Server returned an invalid response")
        }
    }

    suspend fun requestCode(name: String): CodeSession {
        val response = post("request-code", JsonObject().apply {
            addProperty("device_name", name.take(120).ifBlank { "Momo Android phone" })
        })
        return CodeSession(
            pairingId = response.get("pairing_id").asString,
            code = response.get("code").asString,
            pollSecret = response.get("poll_secret").asString,
            expiresAt = response.get("expires_at").asLong
        )
    }

    suspend fun acknowledge(session: CodeSession) {
        post("ack", JsonObject().apply {
            addProperty("pairing_id", session.pairingId)
            addProperty("poll_secret", session.pollSecret)
        })
    }

    suspend fun poll(session: CodeSession): CodePoll {
        val response = post("poll", JsonObject().apply {
            addProperty("pairing_id", session.pairingId)
            addProperty("poll_secret", session.pollSecret)
        })
        val status = response.get("status")?.asString ?: throw IOException("Invalid pairing status")
        val device = if (status == "ready") {
            val token = response.get("token")?.takeUnless { it.isJsonNull }?.asString
            val id = response.get("device_id")?.takeUnless { it.isJsonNull }?.asString
            if (token.isNullOrBlank() || id.isNullOrBlank()) {
                throw IOException("Pairing was completed, but credentials are no longer available. Start a new pairing.")
            }
            BoundDevice(id, token)
        } else null
        return CodePoll(status, device)
    }

    suspend fun claimQr(content: String, name: String): BoundDevice {
        val url = runCatching { Uri.parse(content) }.getOrNull()
            ?: throw IOException("Invalid Momo pairing QR code")
        // Reject QR codes pointing at other sites or carrying arbitrary schemes.
        if (url.scheme != "momo" || url.host != "pair" ||
            url.getQueryParameter("server") != SERVER) {
            throw IOException("QR code does not belong to your Momo AI Server")
        }
        val id = url.getQueryParameter("id") ?: ""
        val ticket = url.getQueryParameter("ticket") ?: ""
        if (!Regex("^[a-fA-F0-9-]{36}$").matches(id) ||
            ticket.length !in 20..256 || !Regex("^[A-Za-z0-9_-]+$").matches(ticket)) {
            throw IOException("Invalid Momo pairing ticket")
        }
        val response = post("claim-qr", JsonObject().apply {
            addProperty("pairing_id", id)
            addProperty("ticket", ticket)
            addProperty("device_name", name.take(120).ifBlank { "Momo Android phone" })
        })
        return BoundDevice(
            deviceId = response.get("device_id").asString,
            token = response.get("token").asString
        )
    }

    fun release() {
        client.dispatcher.executorService.shutdown()
        client.connectionPool.evictAll()
    }
}
